services:
  postgres:
    image: postgres:16
    container_name: pg-container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  rust:
    build:
      context: ./rust-worker
    container_name: rst-container
    environment:
      DATABASE_URL: ${DATABASE_URL}
      ACCOUNT_ID: ${ACCOUNT_ID}
      ACCESS_KEY_ID: ${ACCESS_KEY_ID}
      SECRET_ACCESS_KEY: ${SECRET_ACCESS_KEY}
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  fastapi:
    build:
      context: ./fastapi
    container_name: fastapi-container
    environment:
      DATABASE_URL: ${DATABASE_URL_ASYNCPG}
      ACCOUNT_ID: ${ACCOUNT_ID}
      ACCESS_KEY_ID: ${ACCESS_KEY_ID}
      SECRET_ACCESS_KEY: ${SECRET_ACCESS_KEY}
    ports:
      - "8001:80"
    depends_on:
      - rust
